<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="CACHE-CONTROL" content="NO-CACHE">


    <title>Site Settings</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="The Annual Social Enterprise Conference Website">
    
    <!-- <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.2/css/tachyons.min.css"> -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/main.css ">

    <link rel="icon" type="image/png" href="/images/favicon.png ">
    <link rel="canonical" href="/config-forestryio.yml">
    <link rel="alternate" type="application/rss+xml" title="Wow" href="/feed.xml ">

</head>

  <body class="nunito">
    <!-- Wrapper -->
<header>
Header
</header>


    <h1></h1> 
    ---
title: Wow
email: youremailaddress@gmail.com
description: Some description
baseurl: ''
url: ''
logo-placeholder: images/logo.svg
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
home-link-in-menu: true
collections:
  years:
    output: true
    permalink: "/:title"
  years2:
    output: true
    permalink: "/:title"
  speakers:
    output: true
    permalink: "/speakers/:path/"
  sections:
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    featured-image: ''
- scope:
    path: ''
    type: years
  values:
    layout: years
    title: The Annual SE Conference 201X
    registration: false
    call-for-speakers: true
    main-color: "#444"
    gradient-colors: []
    featured-image: ''
    sections: []
    speakers: []
    speaker-section-index: 0
- scope:
    path: ''
    type: years2
  values:
    layout: years2
    featured-image: ''
    title: The Annual SE Conference 201X
    registration: coming soon
    past: false
    registrationOptions: []
    main-color: "#444"
    gradient-colors: []
    panels: []
- scope:
    path: ''
    type: sections
  values:
    layout: sections
    title: Section Title
    background: ''
    tabs: []
    isSpeakers: false
    speakers: []
- scope:
    path: ''
    type: speakers
  values:
    layout: speakers
    name: Example Name
    short_bio: A little bio
    pic: "/images/pic04.jpg"
timezone: America/New_York
 
    
    <!-- Footer -->
<footer id="footer" class="tc pv4 lh-copy white bg-dark-gradient">
  <div>NU D'Amore-McKim School of Business | USC Marshall School of Business</div>
  © The 14th Annual Social Entrepreneurship Conference
</footer>


<!-- Scripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>

<!-- <script src="https://cdn.jsdelivr.net/velocity/1.5.0/velocity.min.js"></script> -->
<script src="https://cdn.rawgit.com/stutrek/scrollMonitor/19b8820d/scrollMonitor.js"></script>
<script src="https://cdn.rawgit.com/bigspotteddog/ScrollToFixed/a2f9dc0d/jquery-scrolltofixed.js"></script>
<!-- <script src="https://cdn.rawgit.com/ajlkn/jquery.scrollex/cc3e7490/jquery.scrollex.min.js"></script> -->
<script src="/assets/js/main.js"></script>

  </body>
</html>
